-- ============================================================
-- laSolutions - Supabase Schema
-- Ejecutar en: Supabase Dashboard > SQL Editor
-- Incluye: tablas, seed de datos, RLS y funciones auxiliares
-- ============================================================

-- ------------------------------------------------------------
-- 1. PRODUCTOS
-- ------------------------------------------------------------
create table if not exists public.products (
  id integer generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Escritorio', 'Gaming', 'Laptop')),
  brand text not null default 'laSolutions',
  price numeric(10, 2) not null check (price >= 0),
  original_price numeric(10, 2),
  description text not null default '',
  specs jsonb not null default '[]'::jsonb,
  image text not null default 'assets/placeholder.svg',
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2. PROMOCIONES
-- ------------------------------------------------------------
create table if not exists public.promotions (
  id integer generated by default as identity primary key,
  product_id integer not null references public.products (id) on delete cascade,
  discount integer not null check (discount > 0 and discount < 100),
  sale_price numeric(10, 2) not null check (sale_price >= 0),
  label text not null default 'Oferta',
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 3. MENSAJES DE CONTACTO
-- ------------------------------------------------------------
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 4. INDICES
-- ------------------------------------------------------------
create index if not exists idx_products_category on public.products (category);
create index if not exists idx_products_active on public.products (active) where active = true;
create index if not exists idx_promotions_active on public.promotions (active) where active = true;
create index if not exists idx_promotions_product on public.promotions (product_id);
create index if not exists idx_contact_messages_created on public.contact_messages (created_at desc);

-- ------------------------------------------------------------
-- 5. SEED: PRODUCTOS (los 9 originales del sitio)
-- ------------------------------------------------------------
insert into public.products (id, name, category, brand, price, original_price, description, specs, image, featured) values
  (1, 'laSolutions Pro Desktop', 'Escritorio', 'laSolutions', 899, 899,
   'Potente escritorio para profesionales. Ideal para oficina, desarrollo y multitarea exigente.',
   '["Intel Core i5-13400", "16GB DDR4 RAM", "512GB SSD NVMe", "Windows 11 Pro"]', 'assets/placeholder.svg', true),
  (2, 'laSolutions Office Station', 'Escritorio', 'laSolutions', 649, 649,
   'Estacion de trabajo compacta para tareas de oficina, navegacion y productividad basica.',
   '["Intel Core i3-12100", "8GB DDR4 RAM", "256GB SSD", "Windows 11 Home"]', 'assets/placeholder.svg', false),
  (3, 'laSolutions Creator Desktop', 'Escritorio', 'laSolutions', 1299, 1299,
   'Estacion creativa para editores de video, diseno grafico y modelado 3D.',
   '["Intel Core i7-13700", "32GB DDR5 RAM", "1TB SSD NVMe", "Windows 11 Pro"]', 'assets/placeholder.svg', false),
  (4, 'laSolutions Gamer Elite', 'Gaming', 'laSolutions', 1499, 1499,
   'PC gaming de gama media-alta para jugar en 1440p con altas tasas de Frames.',
   '["AMD Ryzen 7 7800X", "NVIDIA RTX 4070 12GB", "32GB DDR5 RAM", "1TB SSD NVMe"]', 'assets/placeholder.svg', true),
  (5, 'laSolutions Gamer Ultra', 'Gaming', 'laSolutions', 2199, 2199,
   'La bestia gaming definitiva. Rendimiento extremo en 4K y streaming simultaneo.',
   '["Intel Core i9-13900K", "NVIDIA RTX 4080 16GB", "64GB DDR5 RAM", "2TB SSD NVMe"]', 'assets/placeholder.svg', false),
  (6, 'laSolutions Gamer Starter', 'Gaming', 'laSolutions', 999, 999,
   'Tu primera PC gaming con rendimiento solido en 1080p para los juegos populares.',
   '["AMD Ryzen 5 7600", "NVIDIA RTX 4060 8GB", "16GB DDR5 RAM", "512GB SSD NVMe"]', 'assets/placeholder.svg', false),
  (7, 'laSolutions Laptop Pro 15', 'Laptop', 'laSolutions', 1099, 1099,
   'Laptop profesional de 15.6 pulgadas con potencia para trabajar desde cualquier lugar.',
   '["Intel Core i7-13700H", "16GB DDR5 RAM", "512GB SSD NVMe", "15.6\" Full HD IPS"]', 'assets/placeholder.svg', true),
  (8, 'laSolutions Laptop Ultra 14', 'Laptop', 'laSolutions', 1399, 1399,
   'Laptop ultradelgada con pantalla 2K, perfecta para profesionales exigentes.',
   '["Intel Core i7-13700H", "32GB DDR5 RAM", "1TB SSD NVMe", "14\" 2K IPS 120Hz"]', 'assets/placeholder.svg', false),
  (9, 'laSolutions Laptop Essential', 'Laptop', 'laSolutions', 599, 599,
   'Laptop accesible para estudios, oficina y uso diario. Excelente relacion precio-calidad.',
   '["Intel Core i5-1235U", "8GB DDR4 RAM", "256GB SSD", "14\" Full HD"]', 'assets/placeholder.svg', false)
on conflict (id) do nothing;

-- ------------------------------------------------------------
-- 6. SEED: PROMOCIONES
-- ------------------------------------------------------------
insert into public.promotions (product_id, discount, sale_price, label, ends_at) values
  (1, 15, 764, 'Oferta de escritorio', now() + interval '2 days 5 hours'),
  (4, 10, 1349, 'Oferta gaming',      now() + interval '1 day 12 hours'),
  (7, 20, 879, 'Oferta laptop',       now() + interval '3 days 8 hours'),
  (9, 25, 449, 'Oferta laptop',       now() + interval '5 hours 30 minutes')
on conflict do nothing;

-- ------------------------------------------------------------
-- 7. ROW LEVEL SECURITY (RLS)
-- ------------------------------------------------------------
alter table public.products         enable row level security;
alter table public.promotions       enable row level security;
alter table public.contact_messages enable row level security;

-- Productos y promociones: lectura publica (anon), escritura solo owner
create policy "products public read"
  on public.products for select
  using (true);

create policy "products owner write"
  on public.products for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "promotions public read"
  on public.promotions for select
  using (true);

create policy "promotions owner write"
  on public.promotions for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Contacto: cualquiera puede insertar (anon), solo owner lee
create policy "contact_messages public insert"
  on public.contact_messages for insert
  with check (true);

create policy "contact_messages owner read"
  on public.contact_messages for select
  using (auth.role() = 'authenticated');

-- ------------------------------------------------------------
-- 8. FUNCION AUXILIAR: datos de catalogo con promo aplicada
-- ------------------------------------------------------------
create or replace function public.get_products_with_promo()
returns json
language sql
stable
as $$
  select json_agg(
    json_build_object(
      'id', p.id,
      'name', p.name,
      'category', p.category,
      'brand', p.brand,
      'price', coalesce(pr.sale_price, p.price),
      'originalPrice', p.price,
      'description', p.description,
      'specs', p.specs,
      'image', p.image,
      'onSale', (pr.sale_price is not null and pr.sale_price < p.price),
      'discount', pr.discount
    )
  )
  from public.products p
  left join public.promotions pr
    on pr.product_id = p.id
   and pr.active = true
   and (pr.starts_at is null or pr.starts_at <= now())
   and (pr.ends_at is null or pr.ends_at > now())
  where p.active = true
  order by p.id;
$$;